title: ProForma: a Standard Proteoform Nomenclature
description: The Consortium for Top Down Proteomics standardized nomenclature for writing fully characterized proteoforms.
theme: jekyll-theme-slate
show_downloads: false